package cli

import (
	"fmt"

	"github.com/solutionforest/k3helper/internal/config"
	"github.com/solutionforest/k3helper/internal/ssh"
	"github.com/solutionforest/k3helper/internal/vm"
	"github.com/spf13/cobra"
)

func newVMCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "vm",
		Short: "Set up k3s on target VMs over SSH",
	}
	cmd.AddCommand(newVMSetupCmd())
	return cmd
}

func newVMSetupCmd() *cobra.Command {
	var (
		targetsPath string
		channel     string
		token       string
		kubeconfig  string
		extraArgs   string
		distro      string
		k8sVersion  string
		cni         string
		noConntrack bool
	)
	cmd := &cobra.Command{
		Use:   "setup",
		Short: "Install k3s server + agents on all nodes in targets file",
		RunE: func(cmd *cobra.Command, args []string) error {
			targets, err := loadTargets(targetsPath)
			if err != nil {
				return err
			}
			// Servers first, then agents. Multiple servers switch k3s to
			// embedded etcd; the first one initialises the cluster.
			var servers, agents []vm.Target
			var conns []*ssh.Client
			// Kept concretely: FetchKubeconfig needs the real client, not the
			// narrower interface Setup takes.
			var firstServer *ssh.Client
			defer func() {
				for _, c := range conns {
					c.Close()
				}
			}()
			for _, n := range targets.Nodes {
				c, err := ssh.Dial(n.SSH())
				if err != nil {
					return fmt.Errorf("connect to %s (%s): %w", n.Name, n.Host, err)
				}
				conns = append(conns, c)
				t := vm.Target{Node: n.SSH(), Client: c}
				if n.Role == "server" {
					if firstServer == nil {
						firstServer = c
					}
					servers = append(servers, t)
				} else {
					agents = append(agents, t)
				}
			}
			if len(servers) == 0 {
				return fmt.Errorf("no server node in targets")
			}
			srvNode := &targets.Nodes[0]
			for i := range targets.Nodes {
				if targets.Nodes[i].Role == "server" {
					srvNode = &targets.Nodes[i]
					break
				}
			}

			if distro == "kubeadm" {
				if err := vm.SetupKubeadm(servers, agents, vm.KubeadmOptions{
					Version:             k8sVersion,
					CNI:                 cni,
					InitExtraArgs:       extraArgs,
					SkipConntrackTuning: noConntrack,
					Progress:            cmd.OutOrStdout(),
				}); err != nil {
					return err
				}
				if kubeconfig != "" {
					if err := vm.FetchKubeadmKubeconfig(firstServer, kubeconfig, srvNode.Host); err != nil {
						return fmt.Errorf("fetch kubeconfig: %w", err)
					}
					fmt.Fprintf(cmd.OutOrStdout(), "kubeconfig written to %s\n", kubeconfig)
				}
				fmt.Fprintln(cmd.OutOrStdout(), "✓ cluster ready")
				return nil
			}
			if distro != "" && distro != "k3s" {
				return fmt.Errorf("unknown --distro %q: use k3s or kubeadm", distro)
			}

			err = vm.Setup(servers, agents, vm.Options{
				Channel:         channel,
				Token:           token,
				ServerExtraArgs: extraArgs,
				AgentExtraArgs:  agentExtraArgs,
				Progress:        cmd.OutOrStdout(),
			})
			if err != nil {
				return err
			}
			if kubeconfig != "" {
				if err := vm.FetchKubeconfig(firstServer, kubeconfig, srvNode.Host); err != nil {
					return fmt.Errorf("fetch kubeconfig: %w", err)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "kubeconfig written to %s\n", kubeconfig)
			}
			fmt.Fprintln(cmd.OutOrStdout(), "✓ cluster ready")
			return nil
		},
	}
	cmd.Flags().StringVarP(&targetsPath, "targets", "t", "targets.yaml", "path to targets YAML")
	cmd.Flags().StringVar(&channel, "channel", "stable", "k3s release channel (stable/latest/vX.Y)")
	cmd.Flags().StringVar(&token, "token", "", "join token (generated by server if empty)")
	cmd.Flags().StringVar(&kubeconfig, "kubeconfig", "", "write fetched kubeconfig to this path")
	cmd.Flags().StringVar(&extraArgs, "server-extra-args", "", "extra args for the server install (k3s install script, or `kubeadm init`)")
	cmd.Flags().StringVar(&distro, "distro", "k3s", "distribution to install: k3s or kubeadm")
	cmd.Flags().StringVar(&k8sVersion, "k8s-version", "", "Kubernetes minor series for kubeadm, e.g. v1.31")
	cmd.Flags().StringVar(&cni, "cni", "flannel", "CNI for kubeadm: flannel or calico")
	cmd.Flags().BoolVar(&noConntrack, "no-conntrack-tuning", false,
		"stop kube-proxy managing nf_conntrack_max; needed where that sysctl is read-only or capped (nested VMs, containers)")
	cmd.Flags().StringVar(&agentExtraArgs, "agent-extra-args", "", "extra args for k3s agent install")
	return cmd
}

var agentExtraArgs string

func toSSHNode(n config.Node) ssh.Node {
	return n.SSH()
}
