package cli

import (
	"fmt"

	"github.com/solutionforest/k3helper/internal/config"
	"github.com/solutionforest/k3helper/internal/ssh"
	"github.com/solutionforest/k3helper/internal/vm"
	"github.com/spf13/cobra"
)

func newVMCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "vm",
		Short: "Set up k3s on target VMs over SSH",
	}
	cmd.AddCommand(newVMSetupCmd())
	return cmd
}

func newVMSetupCmd() *cobra.Command {
	var (
		targetsPath string
		channel     string
		token       string
		kubeconfig  string
		extraArgs   string
	)
	cmd := &cobra.Command{
		Use:   "setup",
		Short: "Install k3s server + agents on all nodes in targets file",
		RunE: func(cmd *cobra.Command, args []string) error {
			targets, err := loadTargets(targetsPath)
			if err != nil {
				return err
			}
			srvNode, err := targets.Server()
			if err != nil {
				return err
			}
			sshSrv := toSSHNode(*srvNode)
			server, err := ssh.Dial(sshSrv)
			if err != nil {
				return fmt.Errorf("connect to server %s: %w", srvNode.Name, err)
			}
			defer server.Close()

			type agentConn struct {
				node   ssh.Node
				client *ssh.Client
			}
			var agents []agentConn
			defer func() {
				for _, a := range agents {
					a.client.Close()
				}
			}()
			for _, n := range targets.Agents() {
				c, err := ssh.Dial(toSSHNode(n))
				if err != nil {
					return fmt.Errorf("connect to agent %s: %w", n.Name, err)
				}
				agents = append(agents, agentConn{node: toSSHNode(n), client: c})
			}

			// convert for vm.Setup (avoid import cycle with a plain struct)
			agentList := make([]struct {
				Node   ssh.Node
				Client *ssh.Client
			}, len(agents))
			for i, a := range agents {
				agentList[i] = struct {
					Node   ssh.Node
					Client *ssh.Client
				}{a.node, a.client}
			}

			err = vm.Setup(server, sshSrv, agentList, vm.Options{
				Channel:         channel,
				Token:           token,
				ServerExtraArgs: extraArgs,
				AgentExtraArgs:  agentExtraArgs,
				Progress:        cmd.OutOrStdout(),
			})
			if err != nil {
				return err
			}
			if kubeconfig != "" {
				if err := vm.FetchKubeconfig(server, kubeconfig); err != nil {
					return fmt.Errorf("fetch kubeconfig: %w", err)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "kubeconfig written to %s\n", kubeconfig)
			}
			fmt.Fprintln(cmd.OutOrStdout(), "✓ cluster ready")
			return nil
		},
	}
	cmd.Flags().StringVarP(&targetsPath, "targets", "t", "targets.yaml", "path to targets YAML")
	cmd.Flags().StringVar(&channel, "channel", "stable", "k3s release channel (stable/latest/vX.Y)")
	cmd.Flags().StringVar(&token, "token", "", "join token (generated by server if empty)")
	cmd.Flags().StringVar(&kubeconfig, "kubeconfig", "", "write fetched kubeconfig to this path")
	cmd.Flags().StringVar(&extraArgs, "server-extra-args", "", "extra args for k3s server install")
	cmd.Flags().StringVar(&agentExtraArgs, "agent-extra-args", "", "extra args for k3s agent install")
	return cmd
}

var agentExtraArgs string

func toSSHNode(n config.Node) ssh.Node {
	return ssh.Node{Host: n.Host, Port: n.Port, User: n.User, Key: n.Key, Local: n.Local}
}
